cart/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('',cart,name='cart'),
    path('<int:product_id>/',add_to_cart,name='add_to_cart'),
    path('remove/<int:product_id>/<int:cart_iteam_id>/',remove_from_cart,name='remove_from_cart'),
    path('remove_cart/<int:product_id>/<int:cart_iteam_id>/',remove_cart,name='remove_cart'),

]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('greatkart.urls')),
    path('store/',include('store.urls')),
    path('cart/',include('cart.urls')),

]+static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

greatkart/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('',home,name='home'),
]

store/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('',store,name='store'),
    path('category/<slug:category_slug>/',store,name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/',product_detail,name='product_detail'),
    path('search/',search,name='search'),
]

cart/models.py
from django.db import models
from store.models import Product,Variation


class Cart(models.Model):

    cart_id     = models.CharField(max_length=250)
    created_at  = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.cart_id

class CartIteam(models.Model):

    product   = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation)
    cart      = models.ForeignKey(Cart, on_delete=models.CASCADE)
    qty       = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def get_subtotal(self):
        return self.product.price * self.qty

    def __str__(self):
        return self.product.product_name

greatkart/models.py
from django.db import models

# Create your models here.

store/models.py
from django.db import models
from category.models import Category
from django.urls import reverse

class Product(models.Model):

    product_name    = models.CharField(max_length=50,unique=True)
    slug            = models.SlugField(max_length=120,unique=True)
    description     = models.TextField(blank=True,max_length=500)
    price           = models.DecimalField(max_digits=5, decimal_places=2)
    image           = models.ImageField(upload_to='photos/products')
    stock           = models.IntegerField()
    is_available    = models.BooleanField(default=True)
    category        = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_at      = models.DateTimeField(auto_now=True)
    modified_at     = models.DateTimeField(auto_now_add=True)


    class Meta:
        verbose_name = ("Product")
        verbose_name_plural = ("Products")

    def __str__(self):
        return self.product_name

    def get_url(self):
        return reverse('product_detail',args=[self.category.cat_slug,self.slug])

variations_categories =(
    ('color','color'),
    ('size','size'),
)

class VariationManager(models.Manager):

    def colors(self):
        return super(VariationManager,self).filter(variation_category='color', is_active=True)

    def size(self):
        return super(VariationManager,self).filter(variation_category='size', is_active=True)



class Variation(models.Model):

    product             = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category  = models.CharField(max_length=50,choices=variations_categories)
    variation_value     = models.CharField(max_length=50)
    is_active           = models.BooleanField(default=True)
    created_at          = models.DateTimeField(auto_now=True)

    objects=VariationManager()

    class Meta:
        verbose_name = ("Variation")
        verbose_name_plural = ("Variations")

    def __str__(self):
        return self.variation_value

cart/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import Http404
from store.models import Product,Variation
from .models import Cart,CartIteam
from django.core.exceptions import ObjectDoesNotExist

def _get_cart_id(request):

    cart = request.session.session_key
    if not cart:
      cart = request.session.create()
    return cart

def cart(request,tot=0,qty=0,cart_iteams=None):
    try:
      grant_tot = 0
      cart =  Cart.objects.get(cart_id=_get_cart_id(request))
      cart_iteams = CartIteam.objects.filter(cart=cart,is_active=True).order_by('id')
      for cart_item in cart_iteams:
        tot +=(cart_item.product.price * cart_item.qty)
        qty += cart_item.qty
      tax = (2* tot)/100
      grant_tot =tax +tot
    except ObjectDoesNotExist:
      print('\033[1;31;40m Cart is empty issue in <app>cart.cart funciton \033[0;0m')
      pass
    context ={
      'total': tot,
      'qty'  : qty,
      'cart_iteams':cart_iteams,
      'tax':tax,
      'grant_tot':grant_tot,
    }
    return render(request,'cart.html',context)

def add_to_cart(request,product_id):

    cureent_product_variation=[]
    product = Product.objects.get(id=product_id)

    if request.method == 'POST':
      for i in request.POST:
          key   =  i
          value = request.POST.get(key)

          try:
            variation = Variation.objects.get(product=product,variation_category__iexact=key,variation_value__iexact=value)
            cureent_product_variation.append(variation)
          except:
            pass
    try :
      cart = Cart.objects.get(cart_id=_get_cart_id(request))
    except Cart.DoesNotExist :
      cart = Cart.objects.create(cart_id=_get_cart_id(request))
    cart.save()


    exits_cart_iteams = CartIteam.objects.filter(product=product,cart=cart).exists()
    iteam=None
    if exits_cart_iteams:
      cart_iteams=CartIteam.objects.filter(product=product,cart=cart)
      current_id=[]
      exit_cart_itm_list=[]
      for iteam in cart_iteams:
        exit_cart_itm_list.append(list(iteam.variations.all()))
        current_id.append(iteam.id)

      if cureent_product_variation in exit_cart_itm_list:
        index= exit_cart_itm_list.index(cureent_product_variation)
        iteam_id = current_id[index]
        iteam = CartIteam.objects.get(product=product,id=iteam_id)
        iteam.qty +=1
        iteam.save()

      else:
        iteam=CartIteam.objects.create(product=product, qty=1,cart=cart)
        if len(cureent_product_variation) > 0:
          iteam.variations.clear()
          iteam.variations.add(*cureent_product_variation)
        iteam.save()

    else :
      cart_iteams = CartIteam.objects.create(
          product=product,
          cart=cart,
          qty=1,
          )
      if len(cureent_product_variation) > 0:
        cart_iteams.variations.add(*cureent_product_variation)
        cart_iteams.save()
    return redirect('cart')

def remove_from_cart(request,product_id,cart_iteam_id):
    try:
      product     = get_object_or_404(Product,id=product_id)
      cart        = Cart.objects.get(cart_id=_get_cart_id(request))
      cart_iteam  = CartIteam.objects.get(cart=cart,product=product,id=cart_iteam_id)
      if cart_iteam.qty >1:
        cart_iteam.qty -=1
        cart_iteam.save()
      else :
        cart_iteam.delete()
      return redirect('cart')
    except:
      print('\033[1;31;40m Cart is empty issue in <app>cart.remove_from_cart funciton \033[0;0m')



def remove_cart(request,product_id,cart_iteam_id):
    try:
      product     = get_object_or_404(Product,id=product_id)
      cart        = Cart.objects.get(cart_id=_get_cart_id(request))
      cart_iteam = CartIteam.objects.get(cart=cart,product=product,id=cart_iteam_id)
      cart_iteam.delete()
      return redirect('cart')
    except:
      print('\033[1;31;40m Cart is empty issue in <app>cart.remove_cart funciton \033[0;0m')

greatkart/views.py
from django.shortcuts import render,get_object_or_404
from store.models import Product

def home(request):

    products = Product.objects.all().filter(is_available= True)
    context = {
        'products' : products
    }

    return render(request,'index.html',context)

store/views.py
from django.shortcuts import render,get_object_or_404,HttpResponse
from .models import Product,Variation
from cart.models import Cart,CartIteam
from cart.views import _get_cart_id
from category.models import Category
from django.core.paginator import Paginator
from django.db.models import Q

def store(request,category_slug=None):

    products_count=0
    if category_slug != None:
        categories  = get_object_or_404(Category,cat_slug=category_slug)
        products     = Product.objects.all().filter(category=categories,is_available= True).order_by('id')
        products_count = len(products)
        page_obj   = Paginator(products,3)
        page_number = request.GET.get("page")
        products_page = page_obj.get_page(page_number)

    else :
        products         = Product.objects.all().filter(is_available= True)
        products_count = len(products)
        page_obj   = Paginator(products,3)
        page_number = request.GET.get("page")
        products_page = page_obj.get_page(page_number)


    context = {
        'products' : products_page,
        'products_count':products_count,
    }
    return render(request,'store.html',context)


def product_detail(request,category_slug,product_slug):

    products    = Product.objects.get(category__cat_slug=category_slug,slug=product_slug)

    context ={
        'product' : products,

    }
    return render(request,'product-detail.html',context)


def search(request,products=None,products_count=0):
    if  request.method == 'GET':
        keyword = request.GET.get('keyword')
        try:
            if keyword :
                products = Product.objects.filter(Q(product_name__icontains=keyword) | Q(description__icontains=keyword)).order_by('-created_at')
                products_count = len(products)
        except :
            print('\033[1;31;40m Error in <store>search \033[0;0m')
            pass


    context = {
        'products' : products,
        'products_count':products_count,
    }
    return render(request,'store.html',context)

greatkart/templates/_base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="cache-control" content="max-age=604800" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<title>GreatKart | One of the Biggest Online Shopping Platform</title>

<link href="{% static 'images/favicon.ico' %}" rel="shortcut icon" type="image/x-icon">

<!-- jQuery -->
<script src="{% static 'js/jquery-2.0.0.min.js' %}" type="text/javascript"></script>

<!-- Bootstrap4 files-->
<script src="{% static 'js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>

<!-- Font awesome 5 -->
<link href="{% static 'fonts/fontawesome/css/all.min.css' %}" type="text/css" rel="stylesheet">

<!-- custom style -->
<link href="{% static 'css/ui.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'css/responsive.css' %}" rel="stylesheet" media="only screen and (max-width: 1200px)" />

<!-- custom javascript -->
<script src="{% static 'js/script.js' %}" type="text/javascript"></script>

<script type="text/javascript">
/// some script

// jquery ready start
$(document).ready(function() {
	// jQuery code

});
// jquery end
</script>

</head>
<body>

  {% include 'include/nav.html' %}
  {% block content %}

  {% endblock content %}

  {% include 'include/footer.html' %}

greatkart/templates/cart.html
{% extends '_base.html' %}
{% load static %}

{% block content %}
<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
{% if cart_iteams %}
		<div class="row">
			<aside class="col-lg-9">
		<div class="card">
		<table class="table table-borderless table-shopping-cart">
		<thead class="text-muted">

		<tr class="small text-uppercase">
			<th scope="col">Product</th>
			<th scope="col" width="120">Quantity</th>
			<th scope="col" width="120">Price</th>
			<th scope="col" class="text-right" width="200"> </th>
		</tr>
		</thead>
		<tbody>
			{% for cart_iteam in cart_iteams %}
				<tr>
					<td>
						<figure class="itemside align-items-center">
							<div class="aside"><img src="{{ cart_iteam.product.image.url }}" class="img-sm"></div>
							<figcaption class="info">
								<a href="{{ cart_iteam.product.get_url}}" class="title text-dark">{{cart_iteam.product.product_name}}</a>
								{% for variation_iteam in cart_iteam.variations.all %}
									<p class="small text-muted">{{variation_iteam.variation_category | capfirst}} : {{variation_iteam.variation_value | capfirst}}</p>
								{% endfor %}
							</figcaption>
						</figure>
					</td>
					<td>
						<!-- col.// -->
									<div class="col">
										<div class="input-group input-spinner">
											<div class="input-group-prepend">
											<a href="{% url 'remove_from_cart' cart_iteam.product.pk cart_iteam.id %}" class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-minus"></i> </a>
											</div>
											<input type="text" class="form-control"  value="{{cart_iteam.qty}}">
											<div class="input-group-append">
											<form action="{% url 'add_to_cart' cart_iteam.product.pk %}" method="post">{% csrf_token %}
												{% for iteam  in cart_iteam.variations.all %}
													<input type="hidden" name="{{iteam.variation_category|lower}}" value="{{iteam.variation_value|capfirst}}">
												{% endfor %}
												<button  class="btn btn-light" type="submit" id="button-minus"> <i class="fa fa-plus"></i> </button>
											</form>
											</div>
										</div> <!-- input-group.// -->
									</div> <!-- col.// -->
					</td>
					<td>
						<div class="price-wrap">
							<var class="price">${{cart_iteam.get_subtotal}} </var>
							<small class="text-muted"> ${{cart_iteam.product.price}}each</small>
						</div> <!-- price-wrap .// -->
					</td>
					<td class="text-right">
						<a href="{% url 'remove_cart' cart_iteam.product.pk cart_iteam.id %}" class="btn btn-danger"> Remove</a>
					</td>
				</tr>

			{% endfor %}

		</tbody>
		</table>
		</div> <!-- card.// -->

			</aside> <!-- col.// -->
			<aside class="col-lg-3">

				<div class="card">
				<div class="card-body">
					<dl class="dlist-align">
						<dt>Total price:</dt>
						<dd class="text-right">${{total}}</dd>
					</dl>
					<dl class="dlist-align">
						<dt>Tax:</dt>
						<dd class="text-right"> ${{tax}}</dd>
					</dl>
					<dl class="dlist-align">
						<dt>Total:</dt>
						<dd class="text-right text-dark b"><strong>${{grant_tot}}</strong></dd>
					</dl>
					<hr>
					<p class="text-center mb-3">
						<img src="{% static './images/misc/payments.png' %}" height="26">
					</p>
					<a href="./place-order.html" class="btn btn-primary btn-block"> Checkout </a>
					<a href="{% url 'store' %}" class="btn btn-light btn-block">Continue Shopping</a>
				</div> <!-- card-body.// -->
				</div> <!-- card.// -->

		</aside> <!-- col.// -->


		</div> <!-- row.// -->
	{% else %}
			<h3 class="text-danger text-center">Your Cart is empty</h3>
			<div class="text-center">
				<a href="{% url 'store' %}" class="btn btn-primary text-center">Continue Shopping</a>
			</div>
{% endif %}
<!-- ============================ COMPONENT 1 END .// ================================= -->

</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

greatkart/templates/dashboard.html
<!DOCTYPE HTML>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="cache-control" content="max-age=604800" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<title>GreatKart | One of the Biggest Online Shopping Platform</title>

<link href="images/favicon.ico" rel="shortcut icon" type="image/x-icon">

<!-- jQuery -->
<script src="js/jquery-2.0.0.min.js" type="text/javascript"></script>

<!-- Bootstrap4 files-->
<script src="js/bootstrap.bundle.min.js" type="text/javascript"></script>
<link href="css/bootstrap.css" rel="stylesheet" type="text/css"/>

<!-- Font awesome 5 -->
<link href="fonts/fontawesome/css/all.min.css" type="text/css" rel="stylesheet">

<!-- custom style -->
<link href="css/ui.css" rel="stylesheet" type="text/css"/>
<link href="css/responsive.css" rel="stylesheet" media="only screen and (max-width: 1200px)" />

<!-- custom javascript -->
<script src="js/script.js" type="text/javascript"></script>

<script type="text/javascript">
/// some script

// jquery ready start
$(document).ready(function() {
	// jQuery code

}); 
// jquery end
</script>

</head>
<body>


<header class="section-header">
<nav class="navbar p-md-0 navbar-expand-sm navbar-light border-bottom">
<div class="container">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTop4">
    <ul class="navbar-nav mr-auto">
    	<li class="nav-item dropdown">
		 	<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">   Language </a>
		    <ul class="dropdown-menu small">
				<li><a class="dropdown-item" href="#">English</a></li>
				<li><a class="dropdown-item" href="#">Arabic</a></li>
				<li><a class="dropdown-item" href="#">Russian </a></li>
		    </ul>
		</li>
		<li class="nav-item dropdown">
			<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"> USD </a>
			<ul class="dropdown-menu small">
				<li><a class="dropdown-item" href="#">EUR</a></li>
				<li><a class="dropdown-item" href="#">AED</a></li>
				<li><a class="dropdown-item" href="#">RUBL </a></li>
		    </ul>
		</li>
    </ul>
    <ul class="navbar-nav">
		<li><a href="#" class="nav-link"> <i class="fa fa-envelope"></i> Email </a></li>
		<li><a href="#" class="nav-link"> <i class="fa fa-phone"></i> Call us </a></li>
	</ul> <!-- list-inline //  -->
  </div> <!-- navbar-collapse .// -->
</div> <!-- container //  -->
</nav>

<section class="header-main border-bottom">
	<div class="container">
<div class="row align-items-center">
	<div class="col-lg-2 col-md-3 col-6">
		<a href="./" class="brand-wrap">
			<img class="logo" src="./images/logo.png">
		</a> <!-- brand-wrap.// -->
	</div>
	<div class="col-lg col-sm col-md col-6 flex-grow-0">
		<div class="category-wrap dropdown d-inline-block float-right">
			<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"> 
				<i class="fa fa-bars"></i> All category 
			</button>
			<div class="dropdown-menu">
				<a class="dropdown-item" href="#">Machinery / Mechanical Parts / Tools </a>
				<a class="dropdown-item" href="#">Consumer Electronics / Home Appliances </a>
				<a class="dropdown-item" href="#">Auto / Transportation</a>
				<a class="dropdown-item" href="#">Apparel / Textiles / Timepieces </a>
				<a class="dropdown-item" href="#">Home & Garden / Construction / Lights </a>
				<a class="dropdown-item" href="#">Beauty & Personal Care / Health </a> 
			</div>
		</div>  <!-- category-wrap.// -->
	</div> <!-- col.// -->
	<a href="./store.html" class="btn btn-outline-primary">Store</a>
	<div class="col-lg  col-md-6 col-sm-12 col">
		<form action="#" class="search">
			<div class="input-group w-100">
			    <input type="text" class="form-control" style="width:60%;" placeholder="Search">
			    
			    <div class="input-group-append">
			      <button class="btn btn-primary" type="submit">
			        <i class="fa fa-search"></i>
			      </button>
			    </div>
		    </div>
		</form> <!-- search-wrap .end// -->
	</div> <!-- col.// -->
	<div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
				<div class="d-flex justify-content-end mb-3 mb-lg-0">
					<div class="widget-header">
						<small class="title text-muted">Welcome guest!</small>
						<div> 
							<a href="./signin.html">Sign in</a> <span class="dark-transp"> | </span>
							<a href="./register.html"> Register</a>
						</div>
					</div>
					<a href="./cart.html" class="widget-header pl-3 ml-3">
						<div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></div>
						<span class="badge badge-pill badge-danger notify">0</span>
					</a>
				</div> <!-- widgets-wrap.// -->
			</div> <!-- col.// -->
</div> <!-- row.// -->
	</div> <!-- container.// -->
</section> <!-- header-main .// -->



</header> <!-- section-header.// -->



<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">

<div class="container">
	<div class="row">
	<aside class="col-md-3">
		<!--   SIDEBAR   -->
		<ul class="list-group">
			<a class="list-group-item active" href="#"> My order history </a>
			<a class="list-group-item" href="#"> Transactions </a>
			<a class="list-group-item" href="#"> Return and refunds </a>
			<a class="list-group-item" href="#">Settings </a>
			<a class="list-group-item" href="#"> My Selling Items </a>
			<a class="list-group-item" href="#"> Received orders </a>
		</ul>
		<br>
		<a class="btn btn-light btn-block" href="#"> <i class="fa fa-power-off"></i> <span class="text">Log out</span> </a> 
		<!--   SIDEBAR .//END   -->
	</aside>
	<main class="col-md-9">
		<article class="card">
		<header class="card-header">
			<strong class="d-inline-block mr-3">Order ID: 6123456789</strong>
			<span>Order Date: 16 December 2018</span>
		</header>
		<div class="card-body">
			<div class="row"> 
				<div class="col-md-8">
					<h6 class="text-muted">Delivery to</h6>
					<p>Michael Jackson <br>  
					Phone +1234567890 Email: myname@pixsellz.com <br>
			    	Location: Home number, Building name, Street 123,  Tashkent, UZB <br> 
			    	P.O. Box: 100123
			 		</p>
				</div>
				<div class="col-md-4">
					<h6 class="text-muted">Payment</h6>
					<span class="text-success">
						<i class="fab fa-lg fa-cc-visa"></i>
					    Visa  **** 4216  
					</span>
					<p>Subtotal: $356 <br>
					 Shipping fee:  $56 <br> 
					 <span class="b">Total:  $456 </span>
					</p>
				</div>
			</div> <!-- row.// -->
		</div> <!-- card-body .// -->
		<div class="table-responsive">
		<table class="table table-hover">
			<tr>
				<td width="65">
					<img src="../images/items/1.jpg" class="img-xs border">
				</td>
				<td> 
					<p class="title mb-0">Product name goes here </p>
					<var class="price text-muted">USD 145</var>
				</td>
				<td> Seller <br> Nike clothing </td>
				<td width="250"> <a href="#" class="btn btn-outline-primary">Track order</a> <a href="#" class="btn btn-light"> Details </a> </td>
			</tr>
			<tr>
				<td>
					<img src="../images/items/2.jpg" class="img-xs border">
				</td>
				<td> 
					<p class="title mb-0">Another name goes here </p>
					<var class="price text-muted">USD 15</var>
				</td>
				<td> Seller <br> ABC shop </td>
				<td> <a href="#" class="btn btn-outline-primary">Track order</a> <a href="#" class="btn btn-light"> Details </a> </td>
			</tr>
			<tr>
				<td>
					<img src="../images/items/3.jpg" class="img-xs border">
				</td>
				<td> 
					<p class="title mb-0">The name of the product  goes here </p>
					<var class="price text-muted">USD 145</var>
				</td>
				<td> Seller <br> Wallmart </td>
				<td> <a href="#" class="btn btn-outline-primary">Track order</a> <a href="#" class="btn btn-light"> Details </a> </td>
			</tr>
		</table>
		</div> <!-- table-responsive .end// -->
		</article> <!-- order-group.// --> 
	</main>
</div> <!-- row.// -->
</div>


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->


<!-- ========================= FOOTER ========================= -->
<footer class="section-footer border-top padding-y">
	<div class="container">
		<p class="float-md-right"> 
			&copy Copyright 2019 All rights reserved
		</p>
		<p>
			<a href="#">Terms and conditions</a>
		</p>
	</div><!-- //container -->
</footer>
<!-- ========================= FOOTER END // ========================= -->



</body>
</html>

greatkart/templates/index.html
{% extends '_base.html' %}
{% load static %}

{% block content %}


<!-- ========================= SECTION MAIN ========================= -->
<section class="section-intro padding-y-sm">
<div class="container">

<div class="intro-banner-wrap">
	<img src="{% static 'images/banners/cover.jpg' %}" class="img-fluid rounded">
</div>

</div> <!-- container //  -->
</section>
<!-- ========================= SECTION MAIN END// ========================= -->

<!-- ========================= SECTION  ========================= -->
<section class="section-name padding-y-sm">
<div class="container">

<header class="section-heading">
	<a href="{% url 'store' %}" class="btn btn-outline-primary float-right">See all</a>
	<h3 class="section-title">Popular products</h3>
</header><!-- sect-heading -->


<div class="row">

	{% for product in products %}
		<div class="col-md-3">
			<div class="card card-product-grid">
				<a href="{{product.get_url}}" class="img-wrap"> <img src="{{product.image.url }}"> </a>
				<figcaption class="info-wrap">
					<a href="{{product.get_url}}" class="title">{{ product.product_name }}</a>
					<div class="price mt-1">$ {{ product.price }}</div> <!-- price-wrap.// -->
				</figcaption>
			</div>
		</div> <!-- col.// -->
	{% endfor %}
</div> <!-- row.// -->

</div><!-- container // -->
</section>
<!-- ========================= SECTION  END// ========================= -->


{% endblock %}

greatkart/templates/product-detail.html
{% extends '_base.html' %}

{% load static %}
{% block content %}
<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
<div class="card">
	<div class="row no-gutters">
		<aside class="col-md-6">
<article class="gallery-wrap">
	<div class="img-big-wrap">
	   <a href="#"><img src="{{product.image.url}}"></a>
	</div> <!-- img-big-wrap.// -->

		<form action="{% url 'add_to_cart' product.id %}" method="post">{% csrf_token %}
				</article> <!-- gallery-wrap .end// -->
						</aside>
						<main class="col-md-6 border-left">
				<article class="content-body">

				<h2 class="title">{{product.product_name}}</h2>

				<div class="mb-3">
					<var class="price h4">${{product.price}}</var>

				</div>

				<p>{{product.description}}</p>


				<hr>

					<div class="row">
						<div class="item-option-select">
							<h6>Choose Color</h6>
							<select name="color" class ="form-control" required>
								<option value="" selected disable>Select</option>
								{% for variation in product.variation_set.colors %}
									<option value="{{variation.variation_value|lower}}">{{variation.variation_value|title}}</option>
								{% endfor %}
							</select>
						</div>
					</div> <!-- row.// -->
					<div class="row">
						<div class="item-option-select">
							<h6>Select Size</h6>
							<select name="size" class ="form-control" required>
								<option value="" selected disable>Select</option>
								{% for size_variation in product.variation_set.size  %}
									<option value="{{size_variation.variation_value|lower}}">{{size_variation.variation_value|title }}</option>
								{% endfor %}
							</select>
						</div>
					</div> <!-- row.// -->
					<hr>
					{% if product.stock <= 0 %}
						<h2 class="text-danger">Out Of Stock</h2>
					{% else %}
							<button type="submit" class="btn  btn-primary"> <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i>  </button>
					{% endif %}
				</article> <!-- product-info-aside .// -->
		</form>
		</main> <!-- col.// -->
	</div> <!-- row.// -->
</div> <!-- card.// -->
<!-- ============================ COMPONENT 1 END .// ================================= -->

<br>

<div class="row">
			<div class="col-md-9">

	<header class="section-heading">
		<h3>Customer Reviews </h3>

	</header>

	<article class="box mb-3">
		<div class="icontext w-100">
			<img src="./images/avatars/avatar1.jpg" class="img-xs icon rounded-circle">
			<div class="text">
				<span class="date text-muted float-md-right">24.04.2020 </span>
				<h6 class="mb-1">Mike John </h6>

			</div>
		</div> <!-- icontext.// -->
		<div class="mt-3">
			<p>
				Dummy comment Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
				quis nostrud exercitation ullamco laboris nisi ut aliquip
			</p>
		</div>
	</article>



	</div> <!-- col.// -->
</div> <!-- row.// -->


</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock content %}